version: "3"
services:
  aplicacao: 
    build: ./aplicacao
    ports: ['8085:8085']
    volumes: ['./aplicacao:/app']
    image: "flaskfin_img"
    environment: 
      - DBSTRING=$DBSTRING
      - IUGU=$IUGU
    